### ISSUE TITLE
Progressive Weapon autotracking bug

### ISSUE THREAD

**Issue by coveleski** [RaceProUK/DLCQuest-APTracker#3]
1. Connect to an AP slot that has been sent 1x DLC Quest: Progressive Weapon or 1x Live Freemium or Die: Progressive Weapon. 
2. Disconnect by clicking the AP label twice.
3. Reconnect to the same slot

Gun and/or Pickaxe will be marked even though the slot only has been sent one copy of Progressive Weapon

**Comment by RaceProUK** [comment]
Unable to reproduce with the latest pack version (0.4.2).

Can you let me know what version of the pack you're running? Also, can you run PopTracker from a console window and copy the output?

**Comment by RaceProUK** [comment]
Never mind: I've managed to trigger the issue myself 😊
